version: "3.7"

services:  

  webapp:
    build: .
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: covid_cinema

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: covid_cinema

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080